name: cardinal-nekrs
channels:
  - nvidia/label/cuda-12.4.1
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - cmake>=3.23
  - ninja
  - cuda-minimal-build=12.4
  - cuda-nvcc
  - cuda-cudart-dev
  - libcurand-dev
  - git-lfs
  - libtirpc
  - jupyterlab
  - ipykernel
  - ipywidgets
  - h5py
  - matplotlib
  - numpy
  - pandas
  - pip:
      - jinja2
      - packaging
      - pyaml
      - psutil
